<?php

namespace App\Repository;

use App\Entity\Media;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $managerRegistry)
    {
        parent::__construct($managerRegistry, Media::class);
    }

    public function countMediaWithFileReference(Media $media) {
        $qb = $this->createQueryBuilder('a');
        $qb ->select('COUNT(a.id)')
            ->andWhere('a.folder = :folder')
            ->andWhere('a.filename = :filename')
            ->andWhere('a.bucket = :bucket')
        ->setParameters([
            'bucket' => $media->getBucket(),
            'filename' => $media->getFilename(),
            'folder' => $media->getFolder(),
        ]);
        return intval($qb->getQuery()->getSingleScalarResult());
    }
}
